exports.appPort=8888;//端口号
exports.userDatabase="users";//user表单数据库名
exports.userTableName="users";//user表单名
exports.dbNameofApp="web_disk";//app使用数据库名(两个表单：hash_files&allow_users);
exports.dbUser="root";//数据库用户名
exports.dbPass="";//数据库密码
exports.dbHost="127.0.0.1";//数据库地址
exports.uploadDir=__dirname+'/tmp/';//上传目录(默认此文件夹tmp目录)
exports.logFile=__dirname+'/log/'+(new Date(Date())).toDateString()+'.log';//历史记录
exports.process_num=1;//进程数
exports.redisPort=6379;//redis端口号
